runtime: python38
instance_class: F4_HIGHMEM
entrypoint: gunicorn -b :$PORT -w 8 main:app.server --timeout 120

handlers:
- url: /static/logo\.png
  static_files: logo.PNG
  upload: logo\.PNG
- url: /static
  static_dir: website/static
- url: /.*
  script: main.app

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: Clutch123!
  CLOUD_SQL_DATABASE_NAME: mysql_database
  CLOUD_SQL_CONNECTION_NAME: comesee-hdb:asia-southeast1:comeseehdb-database